//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SOCY_MIS.SOCY_WS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SOCY_WSSoap", Namespace="http://tempuri.org/")]
    public partial class SOCY_WS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OnlineCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnlineMessageCheckOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback OfficeStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback OfficeValidationOperationCompleted;
        
        private System.Threading.SendOrPostCallback Download_Office_groupOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadTotalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SOCY_WS() {
            this.Url = global::SOCY_MIS.Properties.Settings.Default.SOCY_MIS_SOCY_WS_SOCY_WS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OnlineCheckCompletedEventHandler OnlineCheckCompleted;
        
        /// <remarks/>
        public event OnlineMessageCheckCompletedEventHandler OnlineMessageCheckCompleted;
        
        /// <remarks/>
        public event DownloadDataCompletedEventHandler DownloadDataCompleted;
        
        /// <remarks/>
        public event OfficeStatusCompletedEventHandler OfficeStatusCompleted;
        
        /// <remarks/>
        public event OfficeValidationCompletedEventHandler OfficeValidationCompleted;
        
        /// <remarks/>
        public event Download_Office_groupCompletedEventHandler Download_Office_groupCompleted;
        
        /// <remarks/>
        public event ProcessRecordCompletedEventHandler ProcessRecordCompleted;
        
        /// <remarks/>
        public event DownloadTotalCompletedEventHandler DownloadTotalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnlineCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OnlineCheck() {
            object[] results = this.Invoke("OnlineCheck", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OnlineCheckAsync() {
            this.OnlineCheckAsync(null);
        }
        
        /// <remarks/>
        public void OnlineCheckAsync(object userState) {
            if ((this.OnlineCheckOperationCompleted == null)) {
                this.OnlineCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnlineCheckOperationCompleted);
            }
            this.InvokeAsync("OnlineCheck", new object[0], this.OnlineCheckOperationCompleted, userState);
        }
        
        private void OnOnlineCheckOperationCompleted(object arg) {
            if ((this.OnlineCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnlineCheckCompleted(this, new OnlineCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnlineMessageCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OnlineMessageCheck(string strOfcId, string strVersion) {
            object[] results = this.Invoke("OnlineMessageCheck", new object[] {
                        strOfcId,
                        strVersion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OnlineMessageCheckAsync(string strOfcId, string strVersion) {
            this.OnlineMessageCheckAsync(strOfcId, strVersion, null);
        }
        
        /// <remarks/>
        public void OnlineMessageCheckAsync(string strOfcId, string strVersion, object userState) {
            if ((this.OnlineMessageCheckOperationCompleted == null)) {
                this.OnlineMessageCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnlineMessageCheckOperationCompleted);
            }
            this.InvokeAsync("OnlineMessageCheck", new object[] {
                        strOfcId,
                        strVersion}, this.OnlineMessageCheckOperationCompleted, userState);
        }
        
        private void OnOnlineMessageCheckOperationCompleted(object arg) {
            if ((this.OnlineMessageCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnlineMessageCheckCompleted(this, new OnlineMessageCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DownloadData(string strSsnId, string strLDImpSid, string strLDTable, string strLDObjId, string district_list) {
            object[] results = this.Invoke("DownloadData", new object[] {
                        strSsnId,
                        strLDImpSid,
                        strLDTable,
                        strLDObjId,
                        district_list});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadDataAsync(string strSsnId, string strLDImpSid, string strLDTable, string strLDObjId, string district_list) {
            this.DownloadDataAsync(strSsnId, strLDImpSid, strLDTable, strLDObjId, district_list, null);
        }
        
        /// <remarks/>
        public void DownloadDataAsync(string strSsnId, string strLDImpSid, string strLDTable, string strLDObjId, string district_list, object userState) {
            if ((this.DownloadDataOperationCompleted == null)) {
                this.DownloadDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadDataOperationCompleted);
            }
            this.InvokeAsync("DownloadData", new object[] {
                        strSsnId,
                        strLDImpSid,
                        strLDTable,
                        strLDObjId,
                        district_list}, this.DownloadDataOperationCompleted, userState);
        }
        
        private void OnDownloadDataOperationCompleted(object arg) {
            if ((this.DownloadDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadDataCompleted(this, new DownloadDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OfficeStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OfficeStatus(string strOfcId) {
            object[] results = this.Invoke("OfficeStatus", new object[] {
                        strOfcId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OfficeStatusAsync(string strOfcId) {
            this.OfficeStatusAsync(strOfcId, null);
        }
        
        /// <remarks/>
        public void OfficeStatusAsync(string strOfcId, object userState) {
            if ((this.OfficeStatusOperationCompleted == null)) {
                this.OfficeStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOfficeStatusOperationCompleted);
            }
            this.InvokeAsync("OfficeStatus", new object[] {
                        strOfcId}, this.OfficeStatusOperationCompleted, userState);
        }
        
        private void OnOfficeStatusOperationCompleted(object arg) {
            if ((this.OfficeStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OfficeStatusCompleted(this, new OfficeStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OfficeValidation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OfficeValidation(string strOfcId, string strOfficeDataXML, string strContactDataXML) {
            object[] results = this.Invoke("OfficeValidation", new object[] {
                        strOfcId,
                        strOfficeDataXML,
                        strContactDataXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OfficeValidationAsync(string strOfcId, string strOfficeDataXML, string strContactDataXML) {
            this.OfficeValidationAsync(strOfcId, strOfficeDataXML, strContactDataXML, null);
        }
        
        /// <remarks/>
        public void OfficeValidationAsync(string strOfcId, string strOfficeDataXML, string strContactDataXML, object userState) {
            if ((this.OfficeValidationOperationCompleted == null)) {
                this.OfficeValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOfficeValidationOperationCompleted);
            }
            this.InvokeAsync("OfficeValidation", new object[] {
                        strOfcId,
                        strOfficeDataXML,
                        strContactDataXML}, this.OfficeValidationOperationCompleted, userState);
        }
        
        private void OnOfficeValidationOperationCompleted(object arg) {
            if ((this.OfficeValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OfficeValidationCompleted(this, new OfficeValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Download_Office_group", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Download_Office_group(string strSsnId, string ofc_id) {
            object[] results = this.Invoke("Download_Office_group", new object[] {
                        strSsnId,
                        ofc_id});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Download_Office_groupAsync(string strSsnId, string ofc_id) {
            this.Download_Office_groupAsync(strSsnId, ofc_id, null);
        }
        
        /// <remarks/>
        public void Download_Office_groupAsync(string strSsnId, string ofc_id, object userState) {
            if ((this.Download_Office_groupOperationCompleted == null)) {
                this.Download_Office_groupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownload_Office_groupOperationCompleted);
            }
            this.InvokeAsync("Download_Office_group", new object[] {
                        strSsnId,
                        ofc_id}, this.Download_Office_groupOperationCompleted, userState);
        }
        
        private void OnDownload_Office_groupOperationCompleted(object arg) {
            if ((this.Download_Office_groupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Download_Office_groupCompleted(this, new Download_Office_groupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessRecord", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ProcessRecord(string strSsnId, string strXML) {
            object[] results = this.Invoke("ProcessRecord", new object[] {
                        strSsnId,
                        strXML});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessRecordAsync(string strSsnId, string strXML) {
            this.ProcessRecordAsync(strSsnId, strXML, null);
        }
        
        /// <remarks/>
        public void ProcessRecordAsync(string strSsnId, string strXML, object userState) {
            if ((this.ProcessRecordOperationCompleted == null)) {
                this.ProcessRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessRecordOperationCompleted);
            }
            this.InvokeAsync("ProcessRecord", new object[] {
                        strSsnId,
                        strXML}, this.ProcessRecordOperationCompleted, userState);
        }
        
        private void OnProcessRecordOperationCompleted(object arg) {
            if ((this.ProcessRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessRecordCompleted(this, new ProcessRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadTotal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DownloadTotal(string strOfcId) {
            object[] results = this.Invoke("DownloadTotal", new object[] {
                        strOfcId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadTotalAsync(string strOfcId) {
            this.DownloadTotalAsync(strOfcId, null);
        }
        
        /// <remarks/>
        public void DownloadTotalAsync(string strOfcId, object userState) {
            if ((this.DownloadTotalOperationCompleted == null)) {
                this.DownloadTotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadTotalOperationCompleted);
            }
            this.InvokeAsync("DownloadTotal", new object[] {
                        strOfcId}, this.DownloadTotalOperationCompleted, userState);
        }
        
        private void OnDownloadTotalOperationCompleted(object arg) {
            if ((this.DownloadTotalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadTotalCompleted(this, new DownloadTotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void OnlineCheckCompletedEventHandler(object sender, OnlineCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnlineCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnlineCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void OnlineMessageCheckCompletedEventHandler(object sender, OnlineMessageCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnlineMessageCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnlineMessageCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DownloadDataCompletedEventHandler(object sender, DownloadDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void OfficeStatusCompletedEventHandler(object sender, OfficeStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OfficeStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OfficeStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void OfficeValidationCompletedEventHandler(object sender, OfficeValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OfficeValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OfficeValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void Download_Office_groupCompletedEventHandler(object sender, Download_Office_groupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Download_Office_groupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Download_Office_groupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ProcessRecordCompletedEventHandler(object sender, ProcessRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DownloadTotalCompletedEventHandler(object sender, DownloadTotalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadTotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadTotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591